apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    ccchc.ciCdGitCommit: ${CICD_GIT_COMMIT}
  name: emma-db-redis
  namespace: webchat-test
  labels:
    workload.user.cattle.io/workloadselector: deployment-webchat-test-emma-db-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-webchat-test-emma-db-redis
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: emma-db-redis
        app.kubernetes.io/name: emma-db-redis
    spec:
      containers:
      - env:
        - name: REDIS_INITDB_DATABASE
          value: cccdb
        - name: REDIS_INITDB_ROOT_PASSWORD
          value: 2mL3wkU!
        - name: REDIS_INITDB_ROOT_USERNAME
          value: emma
        - name: FORCE_RESTART_AT
          value: ${CICD_GIT_COMMIT}
        image: ccchc/emma-db-redis:latest
        imagePullPolicy: Always
        name: emma-db-redis
