apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    ccchc.ciCdGitCommit: ${CICD_GIT_COMMIT}
  labels:
    app.kubernetes.io/instance: emma-app-soe
    app.kubernetes.io/name: emma-app-soe
  name: emma-app-soe
  namespace: webchat-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: emma-app-soe
      app.kubernetes.io/name: emma-app-soe
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: emma-app-soe
        app.kubernetes.io/name: emma-app-soe
    spec:
      containers:
      - image: ccchc/emma-app-soe:latest
        imagePullPolicy: Always
        name: emma-app-soe
        ports:
        - containerPort: 9080
          hostPort: 10080
          name: http
          protocol: TCP
        - containerPort: 9443
          hostPort: 10443
          name: https
          protocol: TCP
        env:
        - name: FORCE_RESTART_AT
          value: ${CICD_GIT_COMMIT}
