apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    ccchc.ciCdGitCommit: ${CICD_GIT_COMMIT}
  labels:
    app.kubernetes.io/instance: emma-db-mongo
    app.kubernetes.io/name: emma-db-mongo
  name: emma-db-mongo
  namespace: webchat-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: emma-db-mongo
      app.kubernetes.io/name: emma-db-mongo
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: emma-db-mongo
        app.kubernetes.io/name: emma-db-mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: cccdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: 2mL3wkU!
        - name: MONGO_INITDB_ROOT_USERNAME
          value: emma
        - name: FORCE_RESTART_AT
          value: ${CICD_GIT_COMMIT}
        image: ccchc/emma-db-mongo:latest
        imagePullPolicy: Always
        name: emma-db-mongo
