apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    ccchc.ciCdGitCommit: ${CICD_GIT_COMMIT}
  labels:
    workload.user.cattle.io/workloadselector: deployment-webchat-test-emma-app-webchat
  name: emma-app-webchat
  namespace: webchat-test
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-webchat-test-emma-app-webchat
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: emma-app-webchat
        app.kubernetes.io/name: emma-app-webchat
    spec:
      containers:
      - image: ccchc/emma-app-webchat:latest
        imagePullPolicy: Always
        name: emma-app-webchat
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: FORCE_RESTART_AT
          value: ${CICD_GIT_COMMIT}
